### ISSUE TITLE
How to view a website?

### ISSUE THREAD

**Issue by oren** [twilco/kosmonaut#8]
I am running the executable and I see a window with colourful rectangles. Is there a way to browse the internet?

**Comment by jdm** [comment]
From https://github.com/twilco/kosmonaut#build-and-test:
```
Kosmonaut does not currently support any networking. To render HTML and CSS with Kosmonaut, you may instead run the executable you just built passing any number of HTML and CSS files via the --files (or -f) flag.
```

**Comment by twilco** [comment]
I think the previous state of the readme may have been misleading, so sorry for the confusion.  I'm going to close this one out — feel free to open another with any other questions.
